version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "development"
    schedule:
      interval: "weekly"
